[package]
name = "config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.9.25"
serde = { version = "1.0.189", features = ["derive"] }
rand = { version = "0.8.5", features = [] }