[package]
name = "telegram"
version = "0.1.0"
edition = "2021"
description = "plain and very basic api for telegram"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
